// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\mikha\go\src\url-short\pkg\short\domain\faceService.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/bearname/url-short/pkg/short/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateShortUrl mocks base method.
func (m *MockService) CreateShortUrl(parameter domain.UrlParameter) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortUrl", parameter)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortUrl indicates an expected call of CreateShortUrl.
func (mr *MockServiceMockRecorder) CreateShortUrl(parameter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortUrl", reflect.TypeOf((*MockService)(nil).CreateShortUrl), parameter)
}

// FindUrl mocks base method.
func (m *MockService) FindUrl(shortUrl string) (*domain.Url, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUrl", shortUrl)
	ret0, _ := ret[0].(*domain.Url)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUrl indicates an expected call of FindUrl.
func (mr *MockServiceMockRecorder) FindUrl(shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUrl", reflect.TypeOf((*MockService)(nil).FindUrl), shortUrl)
}
